version = 0.1
[default.deploy.parameters]
stack_name = "springboot-lambda-demo"
resolve_s3 = true
s3_prefix = "springboot-lambda-demo"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
